import DestacadoAbout from "../components/DestacadoAbout";
import ImagenesAbout from "../components/ImagenesAbout";
import ServiciosAbout from "../components/ServiciosAbout";

export const metadata = {
  title: "About - Jaime Hayde",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main id="about-main">
      <section id="first-section-about">
        <h1>Soy un ilustrador apasionado por los gráficos vectoriales.</h1>
      </section>
      <DestacadoAbout />
      <ServiciosAbout />
      <ImagenesAbout />
    </main>
  );
}
