import Image from "next/image";
import TransitionLink from "../components/TransitionLink";
import { getData } from "../components/utils/getData";

export const metadata = {
  title: "Portfolio - Jaime Hayde",
  description: "Generated by create next app",
};

export default async function Portfolio() {
  const data = await getData();

  return (
    <main>
      <section id="portfolio-header">
        <h1>Portfolio</h1>
      </section>
      <section id="portfolio-grid">
        {data.map((proyecto, index) => {
          const featuredImageUrl =
            proyecto._embedded?.["wp:featuredmedia"]?.[0]?.source_url;
          return (
            <TransitionLink
              key={proyecto.id}
              className={`card ${index % 2 === 0 ? "abajo" : "arriba"}`}
              href={`/portfolio/${proyecto.slug}`}
            >
              <h2 className="titulo-proyecto">{proyecto.title?.rendered}</h2>
              <Image
                src={featuredImageUrl}
                width={600}
                height={300}
                placeholder="blur"
                blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCABdAF0DASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAQACA//EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDAIZUJJQEEEQQCSAAgHQJIBIKIggiCASAIEA2kkACFEQgJCBAgECAbSSABCiSQFJAgQASQNghBBJRJICkgQIAJIGwQgEkokkBSQIEAAQD/2Q=="
                alt={proyecto.title?.rendered}
              />
            </TransitionLink>
          );
        })}
      </section>
    </main>
  );
}
