import Image from "next/image";
import TransitionLink from "../components/TransitionLink";
import { getData } from "../components/utils/getData";

export const metadata = {
  title: "Portfolio - Jaime Hayde",
  description: "Generated by create next app",
};

export default async function Portfolio() {
  const data = await getData();

  return (
    <main>
      <section id="portfolio-header">
        <h1>Portfolio</h1>
      </section>
      <section id="portfolio-grid">
        {data.map((proyecto, index) => {
          const featuredImageUrl =
            proyecto._embedded?.["wp:featuredmedia"]?.[0]?.source_url;
          return (
            <TransitionLink
              key={proyecto.id}
              className={`card ${index % 2 === 0 ? "abajo" : "arriba"}`}
              href={`/portfolio/${proyecto.slug}`}
            >
              <h2 className="titulo-proyecto">{proyecto.title?.rendered}</h2>
              <Image
                src={`${featuredImageUrl}`}
                width={600}
                height={300}
                alt="Titulo del proyecto"
              />
            </TransitionLink>
          );
        })}
      </section>
    </main>
  );
}
