import "./globals.css";
import { ReactLenis } from "lenis/react";
import Link from "next/link";
import Transition from "./components/Transition";
import TransitionLink from "./components/TransitionLink";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Jaime Hayde",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <ReactLenis root>
          <Navbar />

          <div id="transition-wrapper">{children}</div>
          <Transition />
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}
