import "./globals.css";
import { ReactLenis } from "lenis/react";
import Link from "next/link";
import Transition from "./components/Transition";
import TransitionLink from "./components/TransitionLink";
import Footer from "./components/Footer";
import { getPosts } from "./components/utils/getData";

export const metadata = {
  title: "Jaime Hayde",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  <getPosts />;
  return (
    <html lang="es">
      <body>
        <ReactLenis root>
          <nav id="navbar">
            <ul>
              <li>
                <TransitionLink href={"/"}>Home</TransitionLink>
              </li>
              <li>
                <TransitionLink href={"/portfolio"}>Portfolio</TransitionLink>
              </li>{" "}
              <li>
                <Link href={""}>Shop</Link>
              </li>{" "}
              <li>
                <TransitionLink href={"/about"}>About</TransitionLink>
              </li>
            </ul>
          </nav>
          <div id="transition-wrapper">{children}</div>
          <Transition />
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}
