import Loader from "./components/Loader";
import Hero from "./components/Hero";
import HomeCarrusel from "./components/HomeCarrusel";
import DestacadoHome from "./components/DestacadoHome";
import ContactHome from "./components/ContactHome";
import Clients from "./components/Clients";
import FooterHome from "./components/FooterHome";

export const metadata = {
  title: "Home - Jaime Hayde",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <Loader />
      <Hero />
      <HomeCarrusel />
      <DestacadoHome />
      <ContactHome />
      <Clients />
      <FooterHome />
    </main>
  );
}
